Repository unseeing-hawk/calorie_tracker, pull requests merged in 2023-12, with the labels that each got.

#76 Nhan/add validation creating product #33
  client-calorie-tracker/src/main/resources/static/resources/css/add_product.css
  client-calorie-tracker/src/main/resources/static/resources/js/add_product.js
  client-calorie-tracker/src/main/resources/templates/add_product.html
Labels: front

#78 nhan/add validation when changing products
  client-calorie-tracker/src/main/resources/static/resources/css/list_product.css
  client-calorie-tracker/src/main/resources/static/resources/js/list_product.js
  client-calorie-tracker/src/main/resources/templates/list_product.html
Labels: front

#77 a.stepanov/add GET /meals/mealtimes endpoint
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/MealRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/MealService.java
Labels: backend

#85 p.pankova/add fatsecretid in product post dto #80
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/dao/ProductDAO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/ProductPostDTO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
Labels: backend

#87 nhan/add error box on registration page
  client-calorie-tracker/src/main/resources/static/resources/css/signup.css
  client-calorie-tracker/src/main/resources/static/resources/js/signup.js
  client-calorie-tracker/src/main/resources/templates/signup.html
Labels: front

#81 p.pankova/get user products #54
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/dao/ProductDAO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/ProductPostDTO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
Labels: backend

#90 nhan/add validation when changing information about food intake
  client-calorie-tracker/src/main/resources/static/resources/css/change_meal.css
  client-calorie-tracker/src/main/resources/static/resources/js/change_meal.js
  client-calorie-tracker/src/main/resources/templates/change_meal.html
Labels: front

#93 nhan/add validation when receiving statistics
  client-calorie-tracker/src/main/resources/static/resources/css/get_summary.css
  client-calorie-tracker/src/main/resources/static/resources/js/get_summary.js
  client-calorie-tracker/src/main/resources/templates/get_summary.html
Labels: front

#92 nhan/remove-a-bug-with-float-number-format
  client-calorie-tracker/src/main/resources/static/resources/js/add_meal.js
  client-calorie-tracker/src/main/resources/static/resources/js/add_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/list_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/settings.js
  client-calorie-tracker/src/main/resources/static/resources/js/signup.js
Labels: front

#40 nhan/add validation to the authorization page
  client-calorie-tracker/src/main/resources/static/resources/css/signin.css
  client-calorie-tracker/src/main/resources/static/resources/js/signin.js
  client-calorie-tracker/src/main/resources/templates/signin.html
Labels: front

#98 nhan/fix problem with buttons not working on registration page
  client-calorie-tracker/src/main/resources/static/resources/css/signup.css
  client-calorie-tracker/src/main/resources/templates/signup.html
Labels: bug, front

#96 nhan/fix a bug with the ability to enter lines larger than provided in the specification
  client-calorie-tracker/src/main/resources/static/resources/css/add_product.css
  client-calorie-tracker/src/main/resources/static/resources/js/add_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/list_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/settings.js
  client-calorie-tracker/src/main/resources/static/resources/js/signup.js
Labels: front

#99 nhan/add on the authorization page when pressing the "Sign in" button transfer data to the EndPome Post/Login
  client-calorie-tracker/src/main/resources/static/resources/css/signin.css
  client-calorie-tracker/src/main/resources/static/resources/js/signin.js
  client-calorie-tracker/src/main/resources/templates/signin.html
Labels: front

#101 Nhan/add transitions via GET endpoints to other pages on the main page when you click on the corresponding buttons
  client-calorie-tracker/src/main/resources/static/resources/css/main.css
  client-calorie-tracker/src/main/resources/static/resources/js/main.js
  client-calorie-tracker/src/main/resources/templates/main.html
Labels: front

#63 nhan/add interaction with the POST /logout endpoint to the main page when the logout button
  client-calorie-tracker/src/main/resources/static/resources/css/main.css
  client-calorie-tracker/src/main/resources/static/resources/js/main.js
  client-calorie-tracker/src/main/resources/templates/main.html
Labels: front

#95 a.stepanov/add put meals
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/MealPutDataDto.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/request/ChangeMealsRequest.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/response/ChangeMealsResponse.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/MealRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/MealService.java
Labels: backend

#100 a.stepanov/add GET /meals/summary endpoint
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/dao/MealDAO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/DaySummaryDTO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/MealRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/MealService.java
Labels: backend

#104 Nhan/add transitions via Get endpoints to all buttons used to navigate
  client-calorie-tracker/src/main/resources/static/resources/css/add_meal.css
  client-calorie-tracker/src/main/resources/static/resources/css/add_product.css
  client-calorie-tracker/src/main/resources/static/resources/css/change_meal.css
  client-calorie-tracker/src/main/resources/static/resources/css/get_summary.css
  client-calorie-tracker/src/main/resources/static/resources/css/list_product.css
  client-calorie-tracker/src/main/resources/static/resources/css/settings.css
  client-calorie-tracker/src/main/resources/static/resources/js/add_meal.js
  client-calorie-tracker/src/main/resources/static/resources/js/add_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/change_meal.js
  client-calorie-tracker/src/main/resources/static/resources/js/get_summary.js
  client-calorie-tracker/src/main/resources/static/resources/js/list_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/settings.js
  client-calorie-tracker/src/main/resources/templates/add_meal.html
  client-calorie-tracker/src/main/resources/templates/add_product.html
  client-calorie-tracker/src/main/resources/templates/change_meal.html
  client-calorie-tracker/src/main/resources/templates/get_summary.html
  client-calorie-tracker/src/main/resources/templates/list_product.html
  client-calorie-tracker/src/main/resources/templates/settings.html
Labels: front

#115 Nhan/correct the application name on all pages
  client-calorie-tracker/src/main/resources/templates/add_meal.html
  client-calorie-tracker/src/main/resources/templates/add_product.html
  client-calorie-tracker/src/main/resources/templates/change_meal.html
  client-calorie-tracker/src/main/resources/templates/get_summary.html
  client-calorie-tracker/src/main/resources/templates/list_product.html
  client-calorie-tracker/src/main/resources/templates/main.html
  client-calorie-tracker/src/main/resources/templates/settings.html
  client-calorie-tracker/src/main/resources/templates/signin.html
  client-calorie-tracker/src/main/resources/templates/signup.html
Labels: front

#117 nhan/add endpoint POST /settings/save to the Save-change button on the settings page
  client-calorie-tracker/src/main/resources/static/resources/js/settings.js
  client-calorie-tracker/src/main/resources/templates/settings.html
Labels: front

#119 v.lukyanov/add save settings post endpoint #116
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/controller/CalorieController.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/controller/exception_handler/ExceptionHandlingController.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/entity/User.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/rest_service/RestApiService.java
  client-calorie-tracker/src/main/resources/templates/settings.html
Labels: front

#123 p.pankova/change and delete products #53
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/ProductPutDTO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/request/ChangeProductsRequest.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/response/ChangeProductsResponse.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
Labels: backend

#122 p.pankova/search products #75
  rest-calorie-tracker/pom.xml
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/dao/ProductDAO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/ProductPostDTO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/FatsecretService.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
Labels: backend

#124 nhan/add interaction with POST /my-products/apply to the product list form when you click on the Apply changes button
  client-calorie-tracker/src/main/resources/static/resources/js/list_product.js
  client-calorie-tracker/src/main/resources/templates/list_product.html
Labels: front

#118 nhan/add interaction with POST /create-product to the form for adding a product when you click on the Add button
  client-calorie-tracker/src/main/resources/static/resources/js/add_product.js
  client-calorie-tracker/src/main/resources/templates/add_product.html
Labels: front

#133 Nhan/add implementation of endpoints to change meal
  client-calorie-tracker/src/main/resources/static/resources/css/change_meal.css
  client-calorie-tracker/src/main/resources/static/resources/js/change_meal.js
  client-calorie-tracker/src/main/resources/templates/change_meal.html
Labels: front

#131 v.lukyanov/add implementation to get summary #129
  client-calorie-tracker/pom.xml
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/controller/CalorieController.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/DaySummaryDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/rest_service/RestApiService.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/utils/DateUtils.java
  client-calorie-tracker/src/main/resources/static/resources/css/get_summary.css
  client-calorie-tracker/src/main/resources/static/resources/css/list_product.css
  client-calorie-tracker/src/main/resources/static/resources/js/get_summary.js
  client-calorie-tracker/src/main/resources/templates/get_summary.html
Labels: front

#136 p.pankova/fix products float validation #83
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/entity/Product.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
Labels: invalid, backend

#135 v.lukyanov/add implementation to change meals #134
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/controller/CalorieController.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/MealGetDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/MealGetDataDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/MealPutDataDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/ProductDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/dom/ChangeMealDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/dom/ProductDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/entity/Meal.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/entity/MealTime.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/requests/ChangeMealsRequest.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/requests/ChangeProductsRequest.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/rest_service/RestApiService.java
  client-calorie-tracker/src/main/resources/static/resources/css/change_meal.css
  client-calorie-tracker/src/main/resources/static/resources/js/change_meal.js
  client-calorie-tracker/src/main/resources/templates/change_meal.html
Labels: front
