Repository unseeing-hawk/calorie_tracker, pull requests merged in 2024-02, with the labels that each got.

#147 P.pankova/change pfc validation #146
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/dto/ProductPutDTO.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/entity/Product.java
Labels: invalid, backend

#143 v.lukyanov/add implementation to add meals #132
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/controller/CalorieController.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/converter/ProductToAddConverter.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/converter/SearchProductDTOConverter.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/MealPostDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/MealPostDataDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/SearchProductDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/dom/AddMealDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/rest_service/RestApiService.java
  client-calorie-tracker/src/main/resources/static/resources/css/add_meal.css
  client-calorie-tracker/src/main/resources/static/resources/js/add_meal.js
  client-calorie-tracker/src/main/resources/templates/add_meal.html
Labels: front

#149 v.lukyanov/fix pfc validation #148
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/dto/ProductPostDTO.java
  client-calorie-tracker/src/main/java/ru/unfatcrew/clientcalorietracker/pojo/entity/Product.java
  client-calorie-tracker/src/main/resources/static/resources/js/add_product.js
  client-calorie-tracker/src/main/resources/static/resources/js/list_product.js
Labels: invalid, front

#151 p.pankova/product tests
  rest-calorie-tracker/pom.xml
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/pojo/request/ChangeProductsRequest.java
  rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
  rest-calorie-tracker/src/test/java/ru/unfatcrew/restcalorietracker/dao/ProductDAOTests.java
  rest-calorie-tracker/src/test/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestControllerTests.java
  rest-calorie-tracker/src/test/java/ru/unfatcrew/restcalorietracker/service/ProductServiceTests.java
  rest-calorie-tracker/src/test/resources/fatsecret-products.json
Labels: backend
